[features]
seeds = false
skip-lint = false

[programs.localnet]
optik_store = "5kat1PUqnGRwMLZhsZ7ryDXcRtwaGPiFe8hEknLQ32dC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "optik-platform/backend/blockchain/programs/optik-store"
]


