[toolchain]
anchor_version = "0.32.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
nft_pairer = "9dKgjdntLkaMpqFoeA4mVMa3gerh9DQbLt4hH2aebANX"
optik_store = "5kat1PUqnGRwMLZhsZ7ryDXcRtwaGPiFe8hEknLQ32dC"

[programs.devnet]
nft_pairer = "9dKgjdntLkaMpqFoeA4mVMa3gerh9DQbLt4hH2aebANX"

[programs.mainnet-beta]
nft_pairer = "REPLACE_WITH_DEPLOYED_PROGRAM_ID"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/nft-pairer"
]


